### ISSUE TITLE
Unable to find the location of Jenkins when use .msi to install Jenkins

### ISSUE THREAD

**Issue by jiakuanghe** [jenkinsci/plugin-installation-manager-tool#521] opened 2023-01-31 22:10 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows 10 21H2

### Reproduction steps

1. Go to [https://www.jenkins.io/download/](https://www.jenkins.io/download/) download the LTS Windows.
2. Execute and install the msi
3. run `.\jenkins-plugin-manager-2.12.9.jar --plugins git:5.0.0`

### Expected Results

/

### Actual Results

java -jar ./jenkins-plugin-manager-2.12.9.jar --plugins git:5.0.0
Unable to open C:\ProgramData\Jenkins\jenkins.war
Unable to get Jenkins version from the WAR file C:\ProgramData\Jenkins\jenkins.war
War not found, installing all plugins: C:\ProgramData\Jenkins\jenkins.war
Done

**Comment by MarkEWaite** [comment] 2023-02-01 20:18
Duplicate of #427

**Closed by MarkEWaite** 2023-02-01 20:18 UTC
Labels: bug
