### ISSUE TITLE
Plugin json containing custom URLs does not use repository mirrors

### ISSUE THREAD

**Issue by MarkRx** [jenkinsci/plugin-installation-manager-tool#287] opened 2021-02-18 22:55 UTC
If a plugin resolves using latest or experimental versions and the plugin metadata json defines a url it ignores any repository mirrors and uses that url directly. This causes problems when proxies/policies restrict hitting the internet directly instead requiring use of a repository mirror.

While mirroring arbitrary urls is not really feasible it should at least detect if the URL is repo.jenkins-ci.org or updates.jenkins.io and use the corresponding mirror if configured.

Code is [here](https://github.com/jenkinsci/plugin-installation-manager-tool/blob/master/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java#L1038) and [here](https://github.com/jenkinsci/plugin-installation-manager-tool/blob/master/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java#L1046)

**Expected:**
URLs in the plugins info json are translated to use the repository mirrors when applicable

**Actual:**
URLs in the plugins info json are hit directly

**Example:** 

jackson2-api

> java.exe -jar jenkins-plugin-manager-2.5.0.jar --jenkins-version 2.263.2 --jenkins-update-center <mirror1>/stable/update-center.json --jenkins-experimental-update-center <mirror1>/experimental/update-center.actual.json --jenkins-plugin-info <mirror1>/current/plugin-versions.json --jenkins-incrementals-repo-mirror <mirror2> --verbose --plugins jackson2-api:latest -d .
> 
> jackson2-api depends on:
> snakeyaml-api 1.27.0
> Setting checksum for: snakeyaml-api to ElUO5EweRQAHyVnzPS/6cW+4xq8hfZhIgPrEjd+FQuA=
> 
> snakeyaml-api has no dependencies
> Setting checksum for: jackson2-api to 2nJnob6/CTeTLvhkPlhf/dubBoAkuJwHSfwf7G/qgfs=
> Setting checksum for: jackson2-api to 2nJnob6/CTeTLvhkPlhf/dubBoAkuJwHSfwf7G/qgfs=
> Will install new plugin jackson2-api 2.12.1
> Will install new plugin snakeyaml-api 1.27.0
> Will use url: https://updates.jenkins.io/download/plugins/snakeyaml-api/1.27.0/snakeyaml-api.hpi to download snakeyaml-api plugin
> Will use url: https://updates.jenkins.io/download/plugins/jackson2-api/2.12.1/jackson2-api.hpi to download jackson2-api plugin
> Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/snakeyaml-api/1.27.0/snakeyaml-api.hpi, or download plugin snakeyaml-api to file
> Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/jackson2-api/2.12.1/jackson2-api.hpi, or download plugin jackson2-api to file
> Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/jackson2-api/2.12.1/jackson2-api.hpi, or download plugin jackson2-api to file
> Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/snakeyaml-api/1.27.0/snakeyaml-api.hpi, or download plugin snakeyaml-api to file
> Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/jackson2-api/2.12.1/jackson2-api.hpi, or download plugin jackson2-api to file
> Downloaded file is not a valid ZIP
> java.io.FileNotFoundException: C:\Users\mrichar2\AppData\Local\Temp\plugin-installation-manager-downloads7889007758612096344\jackson2-api.jpi (The system cannot find the file specified)

**Comment by cronik** [comment] 2022-01-13 15:30
@timja  As a follow on to the #404 change that was just merged, this is the next issue when trying to use an update center proxy behind a firewall.

https://github.com/jenkinsci/plugin-installation-manager-tool/blob/71522f053fa1f80819747604625e6de0ef3e23ea/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java#L1178-L1185

Do you have any thoughts on how to address this issue?

One thought I had was to resolve "latest" versions before the download url is computed. For example:

```
public String getPluginDownloadUrl(Plugin plugin) {
...
  if (StringUtils.isEmpty(pluginVersion)) {
      pluginVersion = "latest";
  }
  
  if ((pluginVersion.equals("latest") || plugin.isLatest()) && latestUcJson != null) {
      JSONObject plugins = latestUcJson.getJSONObject("plugins");
      if (plugins.has(plugin.getName())) {
          JSONObject pluginJson = plugins.getJSONObject(plugin.getName());
          String version = pluginJson.getString("version");
          if (version != null) {
              logVerbose("Resolving latest " + pluginName + " version to: " + version);
              pluginVersion = version;
          }
      }
  }
...
   if (StringUtils.isNotEmpty(pluginUrl)) {
        urlString = pluginUrl;
        logVerbose("Using plugin defined url");
    } else if (pluginVersion.equals("latest") && !StringUtils.isEmpty(jenkinsUcLatest)) {
        urlString = appendPathOntoUrl(dirName(jenkinsUcLatest), "/latest", pluginName + ".hpi");
    } ...
```

This seems to work in local tests. I'm not sure how correct it is overall or if the same technique can be applied to "experimental".

**Comment by timja** [comment] 2022-01-13 15:35
I would need more concrete info to look at.

What plugin can be used to reproduce it?

And where are those urls coming from? Are they in the update-center.json?

Not sure why a plugin would be providing a URL, but since you're hitting it you can probably explain it better

**Comment by cronik** [comment] 2022-01-13 17:17
```
export JENKINS_UC=https://private-mirror.com/jenkins-updated-center/dynamic-stable-2.319.1/update-center-actual.json?version=2.319.1
export JENKINS_UC_DOWNLOAD_URL=https://private-mirror.com/jenkins-updated-center/download/plugins
export JENKINS_UC_EXPERIMENTAL=https://private-mirror.com/jenkins-updated-center/experimental/update-center.actual.json
export JENKINS_INCREMENTALS_REPO_MIRROR=https://private-mirror.com/jenkins-updated-center/incrementals
export JENKINS_PLUGIN_INFO=https://private-mirror.com/jenkins-updated-center/current/plugin-versions.json

java -jar jenkins-plugin-manager-*.jar --plugins docker-plugin
...
Will install new plugin docker-plugin 1.2.6
Will install new plugin docker-java-api 3.1.5.2
...
Will use url: https://updates.jenkins.io/download/plugins/docker-plugin/1.2.6/docker-plugin.hpi to download docker-plugin plugin
Will use url: https://updates.jenkins.io/download/plugins/docker-java-api/3.1.5.2/docker-java-api.hpi to download docker-java-api plugin
...
```

You can see that it resolves to a specific version, but the Plugin instance passed to`getPluginDownloadUrl` still has `plugin.isLatest() == true` so it falls into the that branch that switches to the lastesUcJson plugin url. 

This is the code that sets the specific version and also sets the plugin to latest.
https://github.com/jenkinsci/plugin-installation-manager-tool/blob/71522f053fa1f80819747604625e6de0ef3e23ea/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java#L1089-L1091

I think maybe removing `|| plugin.isLatest()` might be a simple solution.

```java
public String getPluginDownloadUrl(Plugin plugin) {
...
         if (StringUtils.isNotEmpty(pluginUrl)) {
            urlString = pluginUrl;
            logVerbose("Using plugin defined url");
        } else if (pluginVersion.equals("latest") && !StringUtils.isEmpty(jenkinsUcLatest)) {
            urlString = appendPathOntoUrl(dirName(jenkinsUcLatest), "/latest", pluginName + ".hpi");
        }
```

It works in my local testing but I'm not sure the history behind performing the plugin url lookup in `lastesUcJson` and what case it addresses.

**Comment by timja** [comment] 2022-01-13 19:18
It was added as part of this 3 years ago, https://github.com/jenkinsci/plugin-installation-manager-tool/pull/44

If your change works and it passes the current tests and a new one its probably fine

**Closed** 2022-01-14 08:54 UTC
