### ISSUE TITLE
Plugin validation is incorrect

### ISSUE THREAD

**Issue by bericoberin** [jenkinsci/plugin-installation-manager-tool#230] opened 2020-11-20 15:14 UTC
I get an error message when running the plugin-installation-manager:

```
Plugin gradle:1.35 depends on workflow-basic-steps:2.23, but there is an older version defined on the top level - workflow-basic-steps:2.22
```

The problem is that gradle:1.35 dependency is declared as: Pipeline: Basic Steps ≥ 2.16.1 (see site: https://plugins.jenkins.io/gradle/#dependencies)

I need to use Pipeline: Basic Steps 2.22 because it is compatible with the version of Jenkins I'm using.  Going to 2.23 requires my Jenkins to be more advanced than the LTS release.  That also means I can't use the set up with the `jenkinsci/jenkinsfile-runner` docker component.

Just because Pipeline: Basic Steps 2.23 was released 2 weeks ago and now requires Jenkins version 2.263 doesn't mean I want to go to that version.  By policy and self defense our team needs to stay on the LTS release path.  The latest LTS version of Jenkins is 2.249.3 at the time this bug is introduced.

**Comment by timja** [comment] 2020-11-20 15:19
Duplicate of https://github.com/jenkinsci/plugin-installation-manager-tool/issues/193

It should only offer you compatible versions what version of Jenkins core are you using?

**Closed by timja** 2020-11-20 15:19 UTC
