### ISSUE TITLE
Explicit list of plugins even the transitive ones not picking up the lowest but the latest version

### ISSUE THREAD

**Issue by v1v** [jenkinsci/plugin-installation-manager-tool#318] opened 2021-04-07 17:08 UTC
I don't know whether this is the right place though

### What

Given the list plugins and their fixed versions plugins, what's the reason that the manager tool fails when upgrading another plugin?

Let me explain with some information what I've seen.

### Configuration

I'm using the jenkins helm chart -> https://github.com/jenkinsci/helm-charts

And I run a `helm upgrade` after bumping one particular plugin version. There is an explicit list of plugins to ensure any transitive dependencies don't cause any issues.

What version of helm do I use? `2.6.4`
What jenkins version? `2.263.4`
What plugins?
<details><summary>Expand to view</summary>
<p>

```
  installPlugins:
    - ace-editor:1.1
    - ansicolor:0.7.5
    - apache-httpcomponents-client-4-api:4.5.13-1.0
    - artifact-manager-s3:1.13
    - authentication-tokens:1.4
    - authorize-project:1.3.0
    - aws-credentials:1.28.1
    - aws-global-configuration:1.6
    - aws-java-sdk:1.11.976
    - blueocean-autofavorite:1.2.4
    - blueocean-bitbucket-pipeline:1.24.5
    - blueocean-commons:1.24.5
    - blueocean-config:1.24.5
    - blueocean-core-js:1.24.5
    - blueocean-dashboard:1.24.5
    - blueocean-display-url:2.4.1
    - blueocean-events:1.24.5
    - blueocean-git-pipeline:1.24.5
    - blueocean-github-pipeline:1.24.5
    - blueocean-i18n:1.24.5
    - blueocean-jwt:1.24.5
    - blueocean-personalization:1.24.5
    - blueocean-pipeline-api-impl:1.24.5
    - blueocean-pipeline-editor:1.24.5
    - blueocean-pipeline-scm-api:1.24.5
    - blueocean-rest-impl:1.24.5
    - blueocean-rest:1.24.5
    - blueocean-web:1.24.5
    - blueocean:1.24.4
    - bootstrap4-api:4.6.0-3
    - bouncycastle-api:2.20
    - branch-api:2.6.2
    - checks-api:1.6.2
    - cloudbees-bitbucket-branch-source:2.9.7
    - cloudbees-folder:6.15
    - command-launcher:1.2
    - configuration-as-code:1.47
    - copyartifact:1.46
    - credentials-binding:1.24
    - credentials:2.3.15
    - disable-github-multibranch-status:1.2
    - display-url-api:2.3.4
    - docker-commons:1.17
    - docker-workflow:1.26
    - durable-task:1.35
    - echarts-api:5.0.1-1
    - favorite:2.3.2
    - font-awesome-api:5.15.2-2
    - git-client:3.7.1
    - git-server:1.9
    - git:4.7.1
    - github-api:1.123
    - github-branch-source:2.9.7
    - github:1.33.1
    - google-compute-engine:4.3.3
    - google-metadata-plugin:0.3.1
    - google-oauth-plugin:1.0.5
    - google-storage-plugin:1.5.4
    - handlebars:3.0.8
    - handy-uri-templates-2-api:2.1.8-1.0
    - hashicorp-vault-plugin:2.4.0
    - htmlpublisher:1.25
    - inline-pipeline:1.0.1
    - jackson2-api:2.12.1
    - jaxb:2.3.0.1
    - jdk-tool:1.0
    - jenkins-design-language:1.24.5
    - jjwt-api:0.11.2-9.c8b45b8bb173
    - job-dsl:1.74
    - jquery3-api:3.5.1-3
    - jsch:0.1.55.2
    - junit:1.49
    - kubernetes-client-api:4.13.2-1
    - kubernetes-credentials:0.8.0
    - kubernetes:1.28.7
    - lockable-resources:2.10
    - mailer:1.34
    - mask-passwords:2.13
    - matrix-auth:2.6.6
    - matrix-project:1.18
    - metrics:4.0.2.7
    - mock-security-realm:1.5
    - momentjs:1.1.1
    - monitoring:1.86.0
    - oauth-credentials:0.4
    - okhttp-api:3.14.9
    - opentelemetry:0.9-beta-rc247.1bb66b864848
    - pipeline-build-step:2.13
    - pipeline-github:2.7
    - pipeline-githubnotify-step:1.0.5
    - pipeline-graph-analysis:1.10
    - pipeline-input-step:2.12
    - pipeline-milestone-step:1.3.2
    - pipeline-model-api:1.8.4
    - pipeline-model-definition:1.8.4
    - pipeline-model-extensions:1.8.4
    - pipeline-rest-api:2.19
    - pipeline-stage-step:2.5
    - pipeline-stage-tags-metadata:1.8.4
    - pipeline-stage-view:2.19
    - pipeline-utility-steps:2.6.1
    - plain-credentials:1.7
    - plot:2.1.9
    - plugin-util-api:2.1.0
    - popper-api:1.16.1-2
    - pubsub-light:1.13
    - role-strategy:3.1
    - scm-api:2.6.4
    - script-security:1.76
    - slack:2.45
    - snakeyaml-api:1.27.0
    - sse-gateway:1.24
    - ssh-agent:1.20
    - ssh-credentials:1.18.1
    - ssh-slaves:1.31.5
    - structs:1.22
    - timestamper:1.11.8
    - token-macro:2.13
    - trilead-api:1.0.13
    - variant:1.4
    - workflow-aggregator:2.6
    - workflow-api:2.42
    - workflow-basic-steps:2.23
    - workflow-cps-global-lib:2.18
    - workflow-cps:2.90
    - workflow-durable-task-step:2.38
    - workflow-job:2.40
    - workflow-multibranch:2.23
    - workflow-scm-step:2.12
    - workflow-step-api:2.23
    - workflow-support:3.8
```

</p>
</details>

What version did I bump?   `opentelemetry:0.9`

How do I generate the list of installed plugins?

```
Jenkins.instance.pluginManager.each { plugin ->
  println ("    - ${plugin.getShortName()}:${plugin.getVersion()}")
}
```

###  What error did I see?

```
$ k logs jenkins-0 -c init 
...
download plugins
Plugin bootstrap4-api:4.6.0-3 depends on jquery3-api:3.6.0-1, but there is an older version defined on the top level - jquery3-api:3.5.1-3

## then I bump the dependency

$ k logs jenkins-0 -c init 
...
Plugin junit:1.49 depends on checks-api:1.7.0, but there is an older version defined on the top level - checks-api:1.6.2

## then I bump the dependency

$ k logs jenkins-0 -c init 
...
Plugin junit:1.49 depends on echarts-api:5.0.2-1, but there is an older version defined on the top level - echarts-api:5.0.1-1

## then I bump the dependency

$ k logs jenkins-0 -c init 
...
copy plugins to shared volume
finished initialization

```

### Questions

Is this the expected behaviour?
Am I missing something in the configuration that I should be aware of?

Please forgive me if this is not the right repository and I should move this issue to the helm chart.

Thanks

**Comment by timja** [comment] 2021-04-07 18:08
I think a duplicate of https://github.com/jenkinsci/plugin-installation-manager-tool/issues/308#issuecomment-792672010

the helm chart could use `--latest false` as it's safer, the fix is to make latest false more forgiving though I think. So that the defaults work out of the box

**Comment by v1v** [comment] 2021-04-07 20:10
Thanks Tim, I'll give a go, I'll update with the status of it. Thanks again

**Closed** 2021-04-07 21:07 UTC
