### ISSUE TITLE
Installation of a plugin not installing dependency, but UI shows otherwise - can't update it via tool

### ISSUE THREAD

**Issue by fostermi** [jenkinsci/plugin-installation-manager-tool#384] opened 2021-11-24 18:17 UTC
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.303.2
OS: Linux - 5.4.0-90-generic
---
Parameterized-Remote-Trigger:3.1.5.1
bouncycastle-api:2.20
caffeine-api:2.9.2-29.v717aac953ff3
command-launcher:1.2
configuration-as-code:1.54
credentials:2.6.1
jaxb:2.3.0
jdk-tool:1.0
matrix-auth:2.6.8
role-strategy:3.2.0
script-security:1.75
snakeyaml-api:1.29.1
sshd:3.0.3
structs:1.24
token-macro:267.vcdaea6462991
trilead-api:1.0.13
workflow-step-api:2.24
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Docker version 2.303.2-lts
```

### Reproduction steps

- Create simple Dockerfile
```
FROM jenkins/jenkins:2.303.2-lts
COPY --chown=jenkins:jenkins plugins.txt /usr/share/jenkins/ref/plugins.txt
COPY --chown=jenkins:jenkins jenkins-casc /usr/share/jenkins/ref/jenkins-casc
RUN jenkins-plugin-cli --verbose -f /usr/share/jenkins/ref/plugins.txt
```
- Create plugins.txt file
```
trilead-api:latest
credentials:latest
configuration-as-code:latest
role-strategy:latest
Parameterized-Remote-Trigger:latest
```
- Create jenkins-casc file
```
jenkins:
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_PASS}"
```
- Build image
`sudo docker build --force-rm -t jenkins:bouncy .`

- Note installed dependencies
```
Sending build context to Docker daemon  12.29kB
Step 1/4 : FROM jenkins/jenkins:2.303.2-lts
 ---> e4ebf98bd6ca
Step 2/4 : COPY --chown=jenkins:jenkins plugins.txt /usr/share/jenkins/ref/plugins.txt
 ---> f25725b39e94
Step 3/4 : COPY --chown=jenkins:jenkins jenkins-casc /usr/share/jenkins/ref/jenkins-casc
 ---> fd01cfd013b2
Step 4/4 : RUN jenkins-plugin-cli --verbose -f /usr/share/jenkins/ref/plugins.txt
 ---> Running in 1f0be777895a
File containing list of plugins to be downloaded: /usr/share/jenkins/ref/plugins.txt
Reading in plugins from /usr/share/jenkins/ref/plugins.txt

No directory to download plugins entered. Will use default of /usr/share/jenkins/ref/plugins
Using update center https://updates.jenkins.io/update-center.json from JENKINS_UC environment variable
Using experimental update center https://updates.jenkins.io/experimental/update-center.json from JENKINS_UC_EXPERIMENTAL environment variable
Using incrementals mirror https://repo.jenkins-ci.org/incrementals from JENKINS_INCREMENTALS_REPO_MIRROR environment variable
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/plugin-versions.json
No war entered. Will use default of /usr/share/jenkins/jenkins.war

Retrieving update center information
Created cache at: /var/jenkins_home/.cache/jenkins-plugin-management-cli
Update center URL: https://updates.jenkins.io/update-center.json?version=2.303.2
Cache miss for: update-center-2.303.2
Cache miss for: experimental-update-center-2.303.2
Cache miss for: plugin-versions
Couldn't find checksum for trilead-api at version: latest

trilead-api has no dependencies
Setting checksum for: trilead-api to YrRoOOSTz8aVA4K05JddhlzTv7/FitpwS53Zb/EB5Fc=
Couldn't find checksum for credentials at version: latest

credentials depends on: 
configuration-as-code 1.51
structs 1.23
Skipping dependency configuration-as-code:1.51 and its sub-dependencies, because there is a higher version defined on the top level - configuration-as-code:latest
Setting checksum for: structs to tRDZoAaUAZ6BnRbdpMk72rmqr0hOknb3yt8dhfCeN+w=

structs has no dependencies
Setting checksum for: credentials to a67JgswEGSGMDlI6uOKNzIDFDAnthMwa+r8HVWerjSg=
Setting checksum for: credentials to a67JgswEGSGMDlI6uOKNzIDFDAnthMwa+r8HVWerjSg=
Couldn't find checksum for configuration-as-code at version: latest

configuration-as-code depends on: 
caffeine-api 2.9.2-29.v717aac953ff3
snakeyaml-api 1.29.1
Setting checksum for: caffeine-api to 9QX10VH69gbx5WM/dBq/+GIp6I4JvtPbpjqUU2mL5oo=

caffeine-api has no dependencies
Setting checksum for: snakeyaml-api to n4s08eZXpOiDSWY5iLQF4t6tax+ec36PrJc2pptuVZU=

snakeyaml-api has no dependencies
Setting checksum for: configuration-as-code to FnbN7gOoydWcobyGskH/cVRAPryMoQ2PrlDuZOVYlbA=
Setting checksum for: configuration-as-code to FnbN7gOoydWcobyGskH/cVRAPryMoQ2PrlDuZOVYlbA=
Setting checksum for: configuration-as-code to FnbN7gOoydWcobyGskH/cVRAPryMoQ2PrlDuZOVYlbA=
Couldn't find checksum for role-strategy at version: latest

role-strategy depends on: 
caffeine-api 2.9.1-23.v51c4e2c879c8
configuration-as-code 1.51
matrix-auth 2.6.7
Skipping dependency configuration-as-code:1.51 and its sub-dependencies, because there is a higher version defined on the top level - configuration-as-code:1.54
Setting checksum for: caffeine-api to 9QX10VH69gbx5WM/dBq/+GIp6I4JvtPbpjqUU2mL5oo=

caffeine-api has no dependencies
Setting checksum for: matrix-auth to r24O1wfmMQ71yiljaIPs3prvl46hFzMV5GUovcouwoQ=

matrix-auth depends on: 
configuration-as-code 1.35
cloudbees-folder 6.1.0
Skipping dependency configuration-as-code:1.35 and its sub-dependencies, because there is a higher version defined on the top level - configuration-as-code:1.54
Setting checksum for: role-strategy to L6l+tWVy4TEn2/iExjd6u2aqKlcGd0X6WC3nGyy2kac=
Setting checksum for: role-strategy to L6l+tWVy4TEn2/iExjd6u2aqKlcGd0X6WC3nGyy2kac=
Setting checksum for: role-strategy to L6l+tWVy4TEn2/iExjd6u2aqKlcGd0X6WC3nGyy2kac=
Setting checksum for: role-strategy to L6l+tWVy4TEn2/iExjd6u2aqKlcGd0X6WC3nGyy2kac=
Couldn't find checksum for Parameterized-Remote-Trigger at version: latest

Parameterized-Remote-Trigger depends on: 
workflow-step-api 2.13
credentials 2.1.16
script-security 1.34
token-macro 2.3
Skipping dependency credentials:2.1.16 and its sub-dependencies, because there is a higher version defined on the top level - credentials:2.6.1
Setting checksum for: token-macro to ifE1zaT21FznlKL7lEu7Jx1kzm4B2ialVQnk16nMpfg=

token-macro depends on: 
workflow-step-api 2.23
structs 1.22
Setting checksum for: structs to tRDZoAaUAZ6BnRbdpMk72rmqr0hOknb3yt8dhfCeN+w=

structs has no dependencies
Setting checksum for: Parameterized-Remote-Trigger to Xvzek+w5/dXuXqCISjxjoH9QvcfLpT2bg/V2oicJcEQ=
Setting checksum for: Parameterized-Remote-Trigger to Xvzek+w5/dXuXqCISjxjoH9QvcfLpT2bg/V2oicJcEQ=
Setting checksum for: Parameterized-Remote-Trigger to Xvzek+w5/dXuXqCISjxjoH9QvcfLpT2bg/V2oicJcEQ=
Setting checksum for: Parameterized-Remote-Trigger to Xvzek+w5/dXuXqCISjxjoH9QvcfLpT2bg/V2oicJcEQ=
Setting checksum for: Parameterized-Remote-Trigger to Xvzek+w5/dXuXqCISjxjoH9QvcfLpT2bg/V2oicJcEQ=
Will install new plugin Parameterized-Remote-Trigger 3.1.5.1
Will install new plugin role-strategy 3.2.0
Will install new plugin credentials 2.6.1
Will install new plugin structs 1.24
Will install new plugin caffeine-api 2.9.2-29.v717aac953ff3
Will install new plugin token-macro 267.vcdaea6462991
Will install new plugin configuration-as-code 1.54
Will install new plugin snakeyaml-api 1.29.1
Will install new plugin workflow-step-api 2.24
Will install new plugin trilead-api 1.0.13
Will install new plugin matrix-auth 2.6.8
Will use url: https://updates.jenkins.io/download/plugins/configuration-as-code/1.54/configuration-as-code.hpi to download configuration-as-code plugin
Will use url: https://updates.jenkins.io/download/plugins/token-macro/267.vcdaea6462991/token-macro.hpi to download token-macro plugin
Will use url: https://updates.jenkins.io/download/plugins/snakeyaml-api/1.29.1/snakeyaml-api.hpi to download snakeyaml-api plugin
Will use url: https://updates.jenkins.io/download/plugins/workflow-step-api/2.24/workflow-step-api.hpi to download workflow-step-api plugin
Will use url: https://updates.jenkins.io/download/plugins/matrix-auth/2.6.8/matrix-auth.hpi to download matrix-auth plugin
Will use url: https://updates.jenkins.io/download/plugins/trilead-api/1.0.13/trilead-api.hpi to download trilead-api plugin
Will use url: https://updates.jenkins.io/download/plugins/credentials/2.6.1/credentials.hpi to download credentials plugin
Will use url: https://updates.jenkins.io/download/plugins/caffeine-api/2.9.2-29.v717aac953ff3/caffeine-api.hpi to download caffeine-api plugin
Will use url: https://updates.jenkins.io/download/plugins/structs/1.24/structs.hpi to download structs plugin
Will use url: https://updates.jenkins.io/download/plugins/Parameterized-Remote-Trigger/3.1.5.1/Parameterized-Remote-Trigger.hpi to download Parameterized-Remote-Trigger plugin
Will use url: https://updates.jenkins.io/download/plugins/role-strategy/3.2.0/role-strategy.hpi to download role-strategy plugin
Downloaded workflow-step-api from https://mirror.xmission.com/jenkins/plugins/workflow-step-api/2.24/workflow-step-api.hpi (attempt 1 of 3)
Downloaded and validated plugin workflow-step-api
No checksum found for workflow-step-api (probably custom built plugin)
Downloaded structs from https://mirror.xmission.com/jenkins/plugins/structs/1.24/structs.hpi (attempt 1 of 3)
Downloaded and validated plugin structs
Checksum valid for: structs
Downloaded Parameterized-Remote-Trigger from https://mirror.xmission.com/jenkins/plugins/Parameterized-Remote-Trigger/3.1.5.1/Parameterized-Remote-Trigger.hpi (attempt 1 of 3)
Downloaded and validated plugin Parameterized-Remote-Trigger
Checksum valid for: Parameterized-Remote-Trigger
Downloaded role-strategy from https://mirror.xmission.com/jenkins/plugins/role-strategy/3.2.0/role-strategy.hpi (attempt 1 of 3)
Downloaded and validated plugin role-strategy
Downloaded matrix-auth from https://mirror.xmission.com/jenkins/plugins/matrix-auth/2.6.8/matrix-auth.hpi (attempt 1 of 3)
Downloaded and validated plugin matrix-auth
Checksum valid for: matrix-auth
Checksum valid for: role-strategy
Downloaded snakeyaml-api from https://mirror.xmission.com/jenkins/plugins/snakeyaml-api/1.29.1/snakeyaml-api.hpi (attempt 1 of 3)
Downloaded and validated plugin snakeyaml-api
Checksum valid for: snakeyaml-api
Downloaded token-macro from https://mirror.xmission.com/jenkins/plugins/token-macro/267.vcdaea6462991/token-macro.hpi (attempt 1 of 3)
Downloaded and validated plugin token-macro
Downloaded caffeine-api from https://mirror.xmission.com/jenkins/plugins/caffeine-api/2.9.2-29.v717aac953ff3/caffeine-api.hpi (attempt 1 of 3)
Downloaded and validated plugin caffeine-api
Checksum valid for: token-macro
Checksum valid for: caffeine-api
Downloaded credentials from https://mirror.xmission.com/jenkins/plugins/credentials/2.6.1/credentials.hpi (attempt 1 of 3)
Downloaded and validated plugin credentials
Checksum valid for: credentials
Downloaded configuration-as-code from https://mirror.xmission.com/jenkins/plugins/configuration-as-code/1.54/configuration-as-code.hpi (attempt 1 of 3)
Downloaded and validated plugin configuration-as-code
Checksum valid for: configuration-as-code
Downloaded trilead-api from https://mirror.xmission.com/jenkins/plugins/trilead-api/1.0.13/trilead-api.hpi (attempt 1 of 3)
Downloaded and validated plugin trilead-api
Checksum valid for: trilead-api
Done
Removing intermediate container 1f0be777895a
 ---> 9f9cf447c86a
Successfully built 9f9cf447c86a
Successfully tagged jenkins:bouncy
```

- Run container
```
sudo docker run -d \
--name jenkins-casc \
-v jenkins_home:/var/jenkins_home \
-v "$(pwd)"/jenkins-casc:/usr/share/jenkins/ref/jenkins-casc \
-p 8080:8080 \
-e "CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/jenkins-casc" \
-e "JAVA_OPTS=-Djenkins.install.runSetupWizard=false" \
-e "JENKINS_PASS=secret" \
jenkins:bouncy
```
- Login to UI. Look at installed plugins. See `Bouncycastle API` is now installed, but at version 2.20
- Look at Available updates. See `Bouncycastle API` is available to be updated to version 2.25

### Results

Expected result:

Bouncycastle API should be listed as a dependency of Paramterized Remote Trigger when installed via CLI and install the latest version.

Actual result:

Bouncycastle API is installed with Paramterized Remote Trigger, but the `jenkins-plugins-cli` doesn't show that it is. The UI shows that Bouncycastle is installed, but at a lower version than the latest.

Why is there a discrepancy between what `jenkins-plugins-cli` says is a dependency and what is actually getting installed. In this case, Bouncycastle API is somehow getting installed outside of the cli tool. This is making it very difficult to use this tool to find updates and install them programmatically.

**Comment by timja** [comment] 2021-11-24 18:50
Duplicate of https://github.com/jenkinsci/plugin-installation-manager-tool/issues/351#issuecomment-886197894

**Closed by timja** 2021-11-24 18:50 UTC
Labels: bug

**Comment by fostermi** [comment] 2021-11-24 19:00
That bug assumes is suggesting that plugins are installed via the UI. This is not the case. Something other than the `jenkins-pluing-cli` is installing, for example, bouncycastle-api when installing "Parameterized-Remote-Trigger", but its not listed as a dependency of it.

**Comment by fostermi** [comment] 2021-11-24 19:01
Starting a blank Jenkins server and installing the "Parameterized-Remote-Trigger" from the cli looks like this:
```
jenkins@da9bee7f10f7:/$ jenkins-plugin-cli --verbose --plugins Parameterized-Remote-Trigger
No .txt or .yaml file containing list of plugins to be downloaded entered.
No directory to download plugins entered. Will use default of /usr/share/jenkins/ref/plugins
Using update center https://updates.jenkins.io/update-center.json from JENKINS_UC environment variable
Using experimental update center https://updates.jenkins.io/experimental/update-center.json from JENKINS_UC_EXPERIMENTAL environment variable
Using incrementals mirror https://repo.jenkins-ci.org/incrementals from JENKINS_INCREMENTALS_REPO_MIRROR environment variable
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/plugin-versions.json
No war entered. Will use default of /usr/share/jenkins/jenkins.war

Retrieving update center information
Created cache at: /var/jenkins_home/.cache/jenkins-plugin-management-cli
Update center URL: https://updates.jenkins.io/update-center.json?version=2.303.2
Cache miss for: update-center-2.303.2
Cache miss for: experimental-update-center-2.303.2
Cache miss for: plugin-versions
Couldn't find checksum for Parameterized-Remote-Trigger at version: latest

Parameterized-Remote-Trigger depends on: 
workflow-step-api 2.13
credentials 2.1.16
script-security 1.34
token-macro 2.3
Setting checksum for: credentials to a67JgswEGSGMDlI6uOKNzIDFDAnthMwa+r8HVWerjSg=

credentials depends on: 
configuration-as-code 1.51
structs 1.23
Setting checksum for: token-macro to ifE1zaT21FznlKL7lEu7Jx1kzm4B2ialVQnk16nMpfg=

token-macro depends on: 
workflow-step-api 2.23
structs 1.22
Setting checksum for: structs to tRDZoAaUAZ6BnRbdpMk72rmqr0hOknb3yt8dhfCeN+w=

structs has no dependencies
Setting checksum for: Parameterized-Remote-Trigger to Xvzek+w5/dXuXqCISjxjoH9QvcfLpT2bg/V2oicJcEQ=
Setting checksum for: Parameterized-Remote-Trigger to Xvzek+w5/dXuXqCISjxjoH9QvcfLpT2bg/V2oicJcEQ=
Setting checksum for: Parameterized-Remote-Trigger to Xvzek+w5/dXuXqCISjxjoH9QvcfLpT2bg/V2oicJcEQ=
Setting checksum for: Parameterized-Remote-Trigger to Xvzek+w5/dXuXqCISjxjoH9QvcfLpT2bg/V2oicJcEQ=
Setting checksum for: Parameterized-Remote-Trigger to Xvzek+w5/dXuXqCISjxjoH9QvcfLpT2bg/V2oicJcEQ=
Setting checksum for: Parameterized-Remote-Trigger to Xvzek+w5/dXuXqCISjxjoH9QvcfLpT2bg/V2oicJcEQ=
Setting checksum for: Parameterized-Remote-Trigger to Xvzek+w5/dXuXqCISjxjoH9QvcfLpT2bg/V2oicJcEQ=
Will install new plugin Parameterized-Remote-Trigger 3.1.5.1
Will install new plugin credentials 2.6.1
Will install new plugin structs 1.24
Will install new plugin token-macro 267.vcdaea6462991
Will install new plugin workflow-step-api 2.24
Will use url: https://updates.jenkins.io/download/plugins/structs/1.24/structs.hpi to download structs plugin
Will use url: https://updates.jenkins.io/download/plugins/credentials/2.6.1/credentials.hpi to download credentials plugin
Will use url: https://updates.jenkins.io/download/plugins/Parameterized-Remote-Trigger/3.1.5.1/Parameterized-Remote-Trigger.hpi to download Parameterized-Remote-Trigger plugin
Will use url: https://updates.jenkins.io/download/plugins/token-macro/267.vcdaea6462991/token-macro.hpi to download token-macro plugin
Will use url: https://updates.jenkins.io/download/plugins/workflow-step-api/2.24/workflow-step-api.hpi to download workflow-step-api plugin
Downloaded structs from https://mirror.xmission.com/jenkins/plugins/structs/1.24/structs.hpi (attempt 1 of 3)
Downloaded workflow-step-api from https://mirror.xmission.com/jenkins/plugins/workflow-step-api/2.24/workflow-step-api.hpi (attempt 1 of 3)
Downloaded and validated plugin workflow-step-api
No checksum found for workflow-step-api (probably custom built plugin)
Downloaded and validated plugin structs
Checksum valid for: structs
Downloaded Parameterized-Remote-Trigger from https://mirror.xmission.com/jenkins/plugins/Parameterized-Remote-Trigger/3.1.5.1/Parameterized-Remote-Trigger.hpi (attempt 1 of 3)
Downloaded and validated plugin Parameterized-Remote-Trigger
Checksum valid for: Parameterized-Remote-Trigger
Downloaded token-macro from https://mirror.xmission.com/jenkins/plugins/token-macro/267.vcdaea6462991/token-macro.hpi (attempt 1 of 3)
Downloaded and validated plugin token-macro
Checksum valid for: token-macro
Downloaded credentials from https://mirror.xmission.com/jenkins/plugins/credentials/2.6.1/credentials.hpi (attempt 1 of 3)
Downloaded and validated plugin credentials
Checksum valid for: credentials
Done
```
There is nothing about `bouncycastle-api` as a dependency, and it wasn't installed in the UI.

**Comment by timja** [comment] 2021-11-24 19:02
Bouncy castle API is what's known as a 'split plugin' or a 'detached plugins'

https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/jenkins/split-plugins.txt#L23

If you install a plugin with a minimum version of Jenkins prior to when it was split out Jenkins assumes the plugin may be in use and will automatically install it

**Comment by fostermi** [comment] 2021-11-24 19:05
I'm using `2.303.2-lts`. That list says version `2.16`.

**Comment by timja** [comment] 2021-11-24 19:09
One of your dependencies or a dependency of a dependency will have a minimum required version older than 2.16

The remote trigger one requires 1.642.3

You can see it on the plugin site: https://plugins.jenkins.io/Parameterized-Remote-Trigger/

**Comment by fostermi** [comment] 2021-11-29 21:19
So, basically because of detached plugins and https://github.com/jenkinsci/plugin-installation-manager-tool/issues/351, there is no way for this tool to manage plugins programmatically, except during an initial installation or Docker build of a new image to install (new) plugins. All plugin updating has to be done via the UI after deployment.

**Comment by timja** [comment] 2021-11-30 07:29
No, never update them from the UI if it’s managed through code. New detached plugins and dependencies don’t come along very often.

it’s not much effort at all to check occasionally in the plugin manager that all plugins were updated, and at some point the above issue will be implemented
