### ISSUE TITLE
Basic usage throws org.json.JSONException

### ISSUE THREAD

**Issue by EricSalemi** [jenkinsci/plugin-installation-manager-tool#115] opened 2020-07-03 17:43 UTC
Probably something I'm overlooking but running the most basic example fails for me:

```shell
jenkins@5e3eb1c93a51:~$ java -jar jenkins-plugin-manager-1.1.2.jar --war /usr/share/jenkins/jenkins.war --plugin-file /var/jenkins_home/plugins.txt --verbose
File containing list of plugins to be downloaded: /var/jenkins_home/plugins.txt
Reading in plugins from /var/jenkins_home/plugins.txt

No directory to download plugins entered. Will use default of /usr/share/jenkins/ref/plugins
Using update center https://updates.jenkins.io from JENKINS_UC environment variable
Using experimental update center https://updates.jenkins.io/experimental from JENKINS_UC_EXPERIMENTAL environment variable
Using incrementals mirror https://repo.jenkins-ci.org/incrementals from JENKINS_INCREMENTALS_REPO_MIRROR environment variable
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/current/plugin-versions.json
Will use war file: /usr/share/jenkins/jenkins.war
Jenkins version: 2.235.1
No version specific update center for Jenkins version 2.235.1

Retrieving update center information
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.JSONObject.<init>(JSONObject.java:215)
	at org.json.JSONObject.<init>(JSONObject.java:399)
	at io.jenkins.tools.pluginmanager.impl.CacheManager.retrieveFromCache(CacheManager.java:73)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:561)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.getUCJson(PluginManager.java:591)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:141)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:112)
	at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:37)
A JSONObject text must begin with '{' at 1 [character 2 line 1]
```

I'm running this command from inside a docker container using the `jenkins/jenkins:2.235.1` image.

Plugin file:

```text
blueocean:1.23.2
configuration-as-code:1.41
gitlab-plugin:1.5.13
ssh-credentials:1.18.1
job-dsl:1.77
```

What I am doing wrong here?

**Comment by d-zalewski** [comment] 2020-07-09 16:57
+1 having the same issue

**Comment by wokinger** [comment] 2020-07-14 08:43
+1 same here.


```
~ $ java -jar ./jenkins-plugin-manager-1.1.2.jar    --plugin-file ./pluginfile.txt --verbose
File containing list of plugins to be downloaded: ./pluginfile.txt
Reading in plugins from ./pluginfile.txt

No directory to download plugins entered. Will use default of /usr/share/jenkins/ref/plugins
Using update center https://updates.jenkins.io from JENKINS_UC environment variable
Using experimental update center https://updates.jenkins.io/experimental from JENKINS_UC_EXPERIMENTAL environment variable
Using incrementals mirror https://repo.jenkins-ci.org/incrementals from JENKINS_INCREMENTALS_REPO_MIRROR environment variable
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/current/plugin-versions.json
No war entered. Will use default of /usr/share/jenkins/jenkins.war
Jenkins version: 2.235.1
No version specific update center for Jenkins version 2.235.1

Retrieving update center information
Returning cached value for: update-center
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
        at org.json.JSONObject.<init>(JSONObject.java:215)
        at org.json.JSONObject.<init>(JSONObject.java:399)
        at io.jenkins.tools.pluginmanager.impl.CacheManager.retrieveFromCache(CacheManager.java:73)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getJson(PluginManager.java:561)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.getUCJson(PluginManager.java:593)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:141)
        at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:112)
        at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:37)
A JSONObject text must begin with '{' at 1 [character 2 line 1]
```

looks like the json files 
- https://updates.jenkins.io/2.235/update-center.json
- https://updates.jenkins.io/experimental/update-center.json
contain an unexpected string at the begin on the json file: 
`updateCenter.post({.....`
that causes the JSON parser to exit.

in my case a workaround was to point the command to these versions of the json files:

- https://updates.jenkins.io/current/update-center.actual.json
- https://updates.jenkins.io/experimental/update-center.actual.json

Here is my command with the adapted json files
```
java -jar ./jenkins-plugin-manager-1.1.2.jar    --plugin-file ./pluginfile.txt --verbose --jenkins-update-center https://updates.jenkins.io/current/update-center
.actual.json --jenkins-experimental-update-center https://updates.jenkins.io/experimental/update-center.actual.json
```

**Comment by timja** [comment] 2020-07-14 09:13
There's code to filter that out, and it works for me locally.

Haven't been able to reproduce this when I tried =/.

**Comment by timja** [comment] 2020-07-14 09:17
@wokinger what's in your cached update-center file?

it'll be in `~/.cache/jenkins-plugin-management-cli` unless you've overridden it

**Comment by timja** [comment] 2020-07-14 09:19
Hah,

The Jenkins docker image sets an environment variable overriding the update center value we use:


If I run it locally it works, and defaults to the same URL you are using in your fix:
```
$ java -jar plugin-management-cli/target/jenkins-plugin-manager-1.1.3-SNAPSHOT.jar -d plugins --plugins mailer --war ~/Downloads/jenkins.war
No .txt or .yaml file containing list of plugins to be downloaded entered.
Plugin download location: plugins
No CLI option or environment variable set for update center, using default of https://updates.jenkins.io/update-center.actual.json
No CLI option or environment variable set for experimental update center, using default of https://updates.jenkins.io/experimental/update-center.actual.json
No CLI option or environment variable set for incrementals mirror, using default of https://repo.jenkins-ci.org/incrementals
No CLI option or environment variable set for plugin info, using default of https://updates.jenkins.io/current/plugin-versions.json
Will use war file: /Users/timja/Downloads/jenkins.war

Downloading plugin mailer from url: https://updates.jenkins.io/latest/mailer.hpi

Downloading plugin display-url-api from url: https://updates.jenkins.io/download/plugins/display-url-api/2.3.1/display-url-api.hpi
mailer downloaded successfully
```

**Comment by timja** [comment] 2020-07-14 09:22
The URL that is set in the docker image is:

https://updates.jenkins.io

Setting `JENKINS_UC` to either https://updates.jenkins.io/update-center.actual.json or https://updates.jenkins.io/update-center.json works

If you check you cache file you'll see an HTML file.

Either we need to check that the suffix is missing and append it or update the docker image.

**Comment by timja** [comment] 2020-07-28 16:43
Will be fixed by https://github.com/jenkinsci/docker/pull/971

**Comment by timja** [comment] 2020-07-30 21:00
Closed by https://github.com/jenkinsci/plugin-installation-manager-tool/pull/157

**Closed** 2020-07-30 21:00 UTC
